// <auto-generated />
using System;
using ChallengerAgroCare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ChallengerAgroCare.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChallengerAgroCare.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_Do_Comentario");

                    b.Property<int>("Like")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Like_Comentario");

                    b.Property<int?>("PostId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("PostagemId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TxtComment")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Texto_Do_Comentario");

                    b.Property<int?>("UseId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PostagemId");

                    b.HasIndex("UserId");

                    b.ToTable("Tabela_Comentario_Grex_1");
                });

            modelBuilder.Entity("ChallengerAgroCare.Models.Postagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Like")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_Do_Post");

                    b.Property<string>("TxtPost")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Texto_Postagem");

                    b.Property<int?>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tabela_Postagem_Grex_1");
                });

            modelBuilder.Entity("ChallengerAgroCare.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Avatar_Do_Usuario");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("Usuario_Ativo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Nome_Do_Usuario");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Senha_Do_Usuario");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("Data_Do_Cadastro");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("Email_Do_Usuario");

                    b.HasKey("Id");

                    b.ToTable("Tabela_Usuarios_Grex_1");
                });

            modelBuilder.Entity("ChallengerAgroCare.Models.Comentario", b =>
                {
                    b.HasOne("ChallengerAgroCare.Models.Postagem", "Post")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemId");

                    b.HasOne("ChallengerAgroCare.Models.User", "User")
                        .WithMany("Comentarios")
                        .HasForeignKey("UserId");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChallengerAgroCare.Models.Postagem", b =>
                {
                    b.HasOne("ChallengerAgroCare.Models.User", "User")
                        .WithMany("Postagens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChallengerAgroCare.Models.Postagem", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("ChallengerAgroCare.Models.User", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Postagens");
                });
#pragma warning restore 612, 618
        }
    }
}
